apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: isw-service-secrets
  labels:
    app: isw-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: isw-service-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: cbi/isw-service/${ENVIRONMENT}
